all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    jellyfin:
     ansible_host: 192.168.100.100
    centreon-prod:
      ansible_host: 192.168.100.7
    pihole:
      ansible_host: 192.168.100.5
    docker-node01:
      ansible_host: 192.168.100.8
    VLNODE01:
      ansible_host: 192.168.100.9
    docker-node02:
      ansible_host: 192.168.100.11
    gaming-serv-prod:
      ansible_host: 192.168.102.13

physical:
  hosts:
    orion:

virtual:
  hosts:
    pihole::
    jellyfin:
    centreon-prod:
    docker-node01:
    docker-node02:
    SUSE-Node01:

dns:
  hosts:
    pihole:

media:
 hosts:
   jellyfin:

monitoring:
  hosts:
    centreon-prod:
