name: Forgejo Actions Alpine Test
on: [push]

jobs:
  test-alpine:
    runs-on: docker
    container:
      image: alpine:latest
    steps:
      - name: Install dependencies
        # Alpine uses 'apk' instead of 'apt'
        run: apk add --no-cache git nodejs npm

      - name: Check Environment
        run: |
          cat /etc/os-release
          node -v
          echo "Running on Alpine!"