name: Update AdGuard DNS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    runs-on: docker
    container:
      image: hashicorp/terraform:1.5.7

    defaults:
      run:
        working-directory: ./terraform/prod/services

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false
