name: Update AdGuard DNS
on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: docker
    container:
      image: node:trixie # pulled manually due to some weird permission issues ??? #TODO FIX THIS!

    defaults:
      run:
        working-directory: terraform/prod/services/adguard-dns

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          apt-get update && apt-get install -y gnupg curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com trixie main" | tee /etc/apt/sources.list.d/hashicorp.list
          apt-get update && apt-get install terraform

      - name: Create secrets.tfvars
        run: |
          echo 'adguard_admin_password = "${{ secrets.ADGUARD_ADMIN_PASSWORD }}"' > secrets.tfvars

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -var-file="secrets.tfvars"

      - name: Run Terraform Plan and Apply
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@192.168.100.98 << 'EOF'
            cd /home/raif.coonjah/infrastructure/terraform/prod/services/adguard-dns
            terraform plan -var-file="secrets.tfvars" -out=tfplan_adguard-dns
            terraform apply -auto-approve tfplan_adguard-dns
          EOF
