name: Update AdGuard DNS
on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: docker
    container:
      image: node:20-bookworm

    defaults:
      run:
        working-directory: ./terraform/prod/services

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          apt-get update && apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          apt-get update && apt-get install terraform=1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false
